<template><div class="community-profile-page"><CommunitySubheader active-section="perfil" :profile-username="profile.username" /><main><CommunityProfileHeader :profile="profile" :own-profile="ownProfile" @edit="editorOpen=true" /><CommunityProfileTabs :profile="profile" /></main><CommunityProfileEditor v-if="editorOpen" :profile="profile" @close="editorOpen=false" @save="saveProfile" /></div></template>
<script setup lang="ts">
import {profileForUsername,type CommunitySocialProfile} from '~/features/community/data/stage-two.mock'
const route=useRoute(),api=useCommunityApi(),{user,loadSession}=useAuth();const editorOpen=ref(false);const username=computed(()=>String(route.params.username||'').toLowerCase());const profile=ref<CommunitySocialProfile>(profileForUsername(username.value));const ownProfile=computed(()=>Boolean(user.value?.username&&user.value.username.toLowerCase()===username.value));useHead(()=>({title:`${profile.value.displayName} | Community`}));
const achievementRarity=(rarity:string)=>({COMMON:'Comum',RARE:'Raro',EPIC:'Épico',LEGENDARY:'Lendário'}[rarity]||'Comum') as CommunitySocialProfile['achievements'][number]['rarity']
const mediaUrl=(media:unknown)=>{if(typeof media==='string')return media;if(media&&typeof media==='object'){const item=media as Record<string,unknown>;return String(item.url||item.src||item.imageUrl||'')}return ''}
const mergeApiProfile=(value:any)=>{if(!value)return
  const achievements=value.achievementGrants?.map((grant:any)=>({id:grant.achievement.id,name:grant.achievement.name,description:grant.achievement.description,rarity:achievementRarity(grant.achievement.rarity),earnedAt:new Date(grant.grantedAt).toLocaleDateString('pt-BR'),playerPercentage:'—',icon:'trophy' as const}))||[]
  const entries=value.communityPosts?.map((post:any)=>({id:post.id,kind:'publication' as const,title:post.title||'Publicação',content:post.content,createdAt:new Date(post.createdAt).toLocaleDateString('pt-BR')}))||[]
  const media=value.communityPosts?.flatMap((post:any)=>(Array.isArray(post.media)?post.media:[]).map((item:any,index:number)=>({id:`${post.id}-${index}`,imageUrl:mediaUrl(item),alt:post.title||'Mídia da publicação'})).filter((item:any)=>item.imageUrl))||[]
  profile.value={...profile.value,displayName:value.communityProfile?.displayName||value.name||profile.value.displayName,username:value.username||profile.value.username,avatarUrl:value.communityProfile?.avatarUrl||profile.value.avatarUrl,coverUrl:value.communityProfile?.coverUrl||profile.value.coverUrl,bio:value.communityProfile?.bio||profile.value.bio,mainCharacter:{name:value.communityProfile?.mainCharacterName||profile.value.mainCharacter.name,className:value.communityProfile?.mainCharacterClass||profile.value.mainCharacter.className},guild:value.communityProfile?.guildName||profile.value.guild,stats:value.stats||profile.value.stats,achievements:achievements.length?achievements:profile.value.achievements,entries:entries.length?entries:profile.value.entries,media:media.length?media:profile.value.media,privacy:{profile:value.communityProfile?.profileVisibility||profile.value.privacy.profile,characters:value.communityProfile?.charactersVisibility||profile.value.privacy.characters,equipment:value.communityProfile?.equipmentVisibility||profile.value.privacy.equipment,statistics:value.communityProfile?.statisticsVisibility||profile.value.privacy.statistics,guild:value.communityProfile?.guildVisibility||profile.value.privacy.guild,activity:value.communityProfile?.activityVisibility||profile.value.privacy.activity}}
}
const saveProfile=async(value:CommunitySocialProfile)=>{profile.value=value;editorOpen.value=false;if(!ownProfile.value)return;await api.updateProfile({displayName:value.displayName,bio:value.bio,avatarUrl:value.avatarUrl,coverUrl:value.coverUrl,mainCharacterName:value.mainCharacter.name,mainCharacterClass:value.mainCharacter.className,guildName:value.guild,profileVisibility:value.privacy.profile,charactersVisibility:value.privacy.characters,equipmentVisibility:value.privacy.equipment,statisticsVisibility:value.privacy.statistics,guildVisibility:value.privacy.guild,activityVisibility:value.privacy.activity})}
onMounted(async()=>{await loadSession();try{mergeApiProfile(await api.publicProfile(username.value))}catch{/* API offline: mantém a composição visual da primeira versão. */}})
</script>
<style scoped>.community-profile-page{min-height:100vh;background:var(--bm-page-bg);color:var(--bm-text)}.community-profile-page main{display:grid;width:min(100% - 32px,1180px);margin-inline:auto;gap:16px;padding-block:20px 58px}@media(max-width:767px){.community-profile-page main{width:100%;padding:56px 10px 38px}}</style>
