import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'
import type { Prisma } from '@prisma/client'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { PrismaService } from '../../database/prisma.service'
import { AuditService } from '../audit/audit.service'
import type { AuthenticatedUser } from '../auth/auth.types'
import { permissionKeys } from '../auth/permissions'

// PHASE T (2026-09-02) -- the "local import" / effective-state refresh
// Part 25 asked for. Reads a COMMITTED snapshot file
// (docs/economy/legacy-catalog-effective-state-snapshot.json), never a
// live GameServer connection -- apps/api does not and should not hold
// RemoteOps/SSH credentials as a runtime dependency (same boundary
// ADR-0023 already established for the admin control plane's "no real
// sync" decision). The snapshot itself is generated by an operator
// re-running the same read-only RemoteOps download+hash this project's
// Phase R/S audits already used, byte-hash-verified against the live
// server at generation time (see the snapshot's own `sourceFiles`
// field) -- so refreshing effective state is a real, evidenced action,
// just not a live one triggered from inside a request handler.
//
// This service NEVER writes desired-state fields (commercialStatus,
// visible, purchasable, desiredEnabled, priceDesired, etc.) -- only the
// effective* columns, driftStatus, sourceLastReadAt, sourceFingerprint.

type SnapshotRow = {
  key: string
  channel: 'XSHOP' | 'CASHSHOP'
  enabled: boolean
  price?: { coin0?: number; coin1?: number; coin2?: number; coinValue?: number; coinIndex?: number }
  durationDays?: number | null
  durationSeconds?: number | null
  options: Record<string, unknown>
  quantity: number
  fingerprint: string
}

type Snapshot = {
  generatedAt: string
  sourceFiles: Array<{ file: string; sha256: string; bytes: number }>
  totals: { xshop: number; cashshop: number }
  rows: SnapshotRow[]
}

const hasPermission = (user: AuthenticatedUser, permission: string) => user.permissions.includes('*') || user.permissions.includes(permission)

@Injectable()
export class LegacyCatalogEffectiveStateService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService
  ) {}

  private async readSnapshot(): Promise<Snapshot> {
    const candidates = [
      path.resolve(process.cwd(), 'docs/economy/legacy-catalog-effective-state-snapshot.json'),
      path.resolve(process.cwd(), '../../docs/economy/legacy-catalog-effective-state-snapshot.json'),
      path.resolve(__dirname, '../../../../../docs/economy/legacy-catalog-effective-state-snapshot.json')
    ]
    let lastError: unknown
    for (const candidate of candidates) {
      try {
        return JSON.parse(await readFile(candidate, 'utf8')) as Snapshot
      } catch (error) {
        lastError = error
      }
    }
    throw new NotFoundException(`Snapshot de estado efetivo nao encontrado: ${lastError instanceof Error ? lastError.message : 'caminhos verificados sem sucesso'}`)
  }

  // Part 6's drift comparison, applied per-row. Only compares fields the
  // Portal has a real, meaningful desired-state opinion about -- a row
  // with every desired field still at its default (never edited by an
  // admin) is reported IN_SYNC rather than a false DRIFT against
  // whatever the GameServer happens to have, since "the Portal has no
  // opinion yet" is not the same claim as "these values match."
  private computeDrift(row: { desiredEnabled: boolean; priceDesired: number | null; currencyDesired: string | null }, effective: SnapshotRow): 'IN_SYNC' | 'DRIFT_DETECTED' {
    if (row.desiredEnabled !== effective.enabled) return 'DRIFT_DETECTED'
    if (row.priceDesired !== null) {
      const effectivePrice = effective.price?.coin0 ?? effective.price?.coinValue ?? null
      if (effectivePrice !== null && row.priceDesired !== effectivePrice) return 'DRIFT_DETECTED'
    }
    return 'IN_SYNC'
  }

  async refresh(user: AuthenticatedUser) {
    if (!hasPermission(user, permissionKeys.adminStoreLegacyCatalogEdit)) {
      throw new ForbiddenException('Voce nao possui permissao para atualizar o estado efetivo do catalogo legado.')
    }
    const snapshot = await this.readSnapshot()
    let updated = 0
    let driftCount = 0
    let inSyncCount = 0
    let unmatched = 0

    for (const row of snapshot.rows) {
      const existing = await this.prisma.legacyCatalogItem.findUnique({ where: { channel_legacyKey: { channel: row.channel, legacyKey: row.key } } })
      if (!existing) {
        unmatched += 1
        continue
      }
      const effectivePrice = row.price?.coin0 ?? row.price?.coinValue ?? null
      const effectiveCurrency = row.channel === 'XSHOP' ? 'WCoinC/WCoinP/GoblinPoint' : `CashShop points (CoinIndex=${row.price?.coinIndex ?? 508})`
      const effectiveDurationSeconds = row.channel === 'XSHOP' ? (row.durationDays ? row.durationDays * 86400 : null) : (row.durationSeconds ?? null)
      const driftStatus = this.computeDrift(
        { desiredEnabled: existing.desiredEnabled, priceDesired: existing.priceDesired, currencyDesired: existing.currencyDesired },
        row
      )
      if (driftStatus === 'DRIFT_DETECTED') driftCount += 1
      else inSyncCount += 1

      await this.prisma.legacyCatalogItem.update({
        where: { id: existing.id },
        data: {
          effectiveEnabled: row.enabled,
          effectivePrice,
          effectiveCurrency,
          effectiveDurationSeconds,
          effectiveOptions: row.options as Prisma.InputJsonValue,
          sourceLastReadAt: new Date(snapshot.generatedAt),
          sourceFingerprint: row.fingerprint,
          effectiveStateCheckedBy: user.id,
          driftStatus
          // Deliberately NOT updated: commercialStatus, visible,
          // purchasable, desiredEnabled, priceDesired, currencyDesired,
          // durationDesiredDays, availableFrom/Until, openBetaAllowed,
          // fullReleaseAllowed, purchaseLimitDesired, internalNotes,
          // blockReason, linkedShopProductId -- every desired-state
          // field an admin may have set is preserved untouched.
        }
      })
      updated += 1
    }

    await this.audit.record({
      actorId: user.id,
      actorUsername: user.username,
      actorRole: user.role,
      action: 'admin.store.legacy-catalog.effective-state-refreshed',
      targetType: 'LegacyCatalogItem',
      afterData: { updated, driftCount, inSyncCount, unmatched, snapshotGeneratedAt: snapshot.generatedAt },
      workDescription: `Estado efetivo do catalogo legado atualizado a partir do snapshot: ${updated} linhas, ${driftCount} com drift, ${unmatched} sem correspondencia no Portal.`
    })

    return { updated, driftCount, inSyncCount, unmatched, snapshotGeneratedAt: snapshot.generatedAt, sourceFiles: snapshot.sourceFiles }
  }
}
