<script setup lang="ts">
import { FileText, Image, Repeat2 } from 'lucide-vue-next'
import type { CommunitySocialProfile } from '~/features/community/types/profile'

const props = defineProps<{ profile: CommunitySocialProfile }>()
const active = ref<'media' | 'publications' | 'shared'>('media')
const tabs = [{ key: 'media', label: 'Mídia', icon: Image }, { key: 'publications', label: 'Publicações', icon: FileText }, { key: 'shared', label: 'Compartilhados', icon: Repeat2 }] as const
const entries = computed(() => props.profile.entries.filter((item) => item.kind === (active.value === 'publications' ? 'publication' : 'repost')))
</script>

<template><section class="community-profile-content"><nav role="tablist" aria-label="Conteúdo do perfil"><button v-for="tab in tabs" :key="tab.key" type="button" role="tab" :aria-selected="active === tab.key" :class="{ 'is-active': active === tab.key }" @click="active = tab.key"><component :is="tab.icon" class="size-4" />{{ tab.label }}</button></nav><div v-if="active === 'media'" class="community-profile-media"><article v-for="media in profile.media" :key="media.id"><img :src="media.imageUrl" :alt="media.alt"><span>{{ media.alt }}</span></article></div><div v-else class="community-profile-entries"><article v-for="entry in entries" :key="entry.id"><span v-if="entry.kind === 'repost'">Compartilhado</span><h2>{{ entry.title }}</h2><p>{{ entry.content }}</p><small>{{ entry.createdAt }}<template v-if="entry.author"> · @{{ entry.author }}</template></small></article><p v-if="!entries.length" class="community-profile-empty">Nenhum conteúdo publicado nesta área.</p></div></section></template>

<style scoped>
.community-profile-content{border:1px solid var(--bm-border);border-radius:10px;background:var(--bm-surface-strong);box-shadow:var(--shadow-panel)}.community-profile-content nav{display:flex;overflow-x:auto;border-bottom:1px solid var(--bm-border);padding-inline:12px}.community-profile-content nav button{display:flex;min-height:48px;flex:1;align-items:center;justify-content:center;gap:7px;border-bottom:2px solid transparent;padding:0 14px;color:var(--bm-muted);font-size:.67rem;font-weight:900;white-space:nowrap}.community-profile-content nav button.is-active{border-color:var(--bm-red);color:var(--bm-wine)}.community-profile-media{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:3px;padding:3px}.community-profile-media article{position:relative;aspect-ratio:1;overflow:hidden;background:var(--bm-surface)}.community-profile-media img{width:100%;height:100%;object-fit:cover;transition:transform .2s ease}.community-profile-media article:hover img{transform:scale(1.025)}.community-profile-media span{position:absolute;inset:auto 0 0;padding:24px 10px 8px;background:linear-gradient(transparent,rgb(0 0 0/.72));color:white;font-size:.6rem;opacity:0;transition:opacity .2s}.community-profile-media article:hover span{opacity:1}.community-profile-entries{display:grid;gap:10px;padding:14px}.community-profile-entries article{border:1px solid var(--bm-border);border-radius:8px;padding:15px}.community-profile-entries article>span{display:inline-flex;border:1px solid var(--bm-border);border-radius:4px;padding:3px 6px;color:var(--bm-wine);font-size:.54rem;font-weight:900;text-transform:uppercase}.community-profile-entries article>span.is-collab{border-color:#8d5a09;color:#8d5a09}.community-profile-entries h2{margin-top:8px;color:var(--bm-heading);font-family:Cinzel,serif;font-size:.9rem}.community-profile-entries p{margin-top:5px;color:var(--bm-muted);font-size:.72rem;line-height:1.6}.community-profile-entries small{display:block;margin-top:9px;color:var(--bm-muted);font-size:.58rem}.community-profile-empty{padding:40px;text-align:center;color:var(--bm-muted);font-size:.72rem}@media(max-width:640px){.community-profile-content nav{padding:0}.community-profile-content nav button{min-width:108px}.community-profile-media{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
