<script setup lang="ts">
import { Save, X } from 'lucide-vue-next'
import type { CommunitySocialProfile } from '~/features/community/data/stage-two.mock'
import { usernamePolicy } from '~/features/community/data/stage-two.mock'
const props=defineProps<{profile:CommunitySocialProfile}>();const emit=defineEmits<{close:[];save:[CommunitySocialProfile]}>();const form=reactive(structuredClone(toRaw(props.profile)));const submit=()=>emit('save',structuredClone(toRaw(form)))
</script>
<template><Teleport to="body"><div class="community-editor-backdrop" @click.self="emit('close')"><form class="community-editor" @submit.prevent="submit"><header><div><span>Meu perfil</span><h2>Editar perfil social</h2></div><UButton color="neutral" variant="ghost" square aria-label="Fechar" @click="emit('close')"><X class="size-4" /></UButton></header><div class="community-editor__body"><section><h3>Identidade</h3><label>Nome público<input v-model="form.displayName" maxlength="100"></label><label>Bio<textarea v-model="form.bio" maxlength="2000" /></label><div class="community-editor__two"><label>Personagem principal<input v-model="form.mainCharacter.name"></label><label>Classe<input v-model="form.mainCharacter.className"></label></div><label>Guild<input v-model="form.guild"></label></section><section><h3>Imagens</h3><label>URL do avatar<input v-model="form.avatarUrl" type="url"></label><label>URL da capa<input v-model="form.coverUrl" type="url"></label><label>Username<input :value="form.username" disabled><small>Alteração futura sujeita a validação, histórico e cooldown de {{ usernamePolicy.cooldownDays }} dias.</small></label></section><section class="community-editor__privacy"><h3>Privacidade</h3><label>Perfil<select v-model="form.privacy.profile"><option>PUBLIC</option><option>FOLLOWERS</option><option>PRIVATE</option></select></label><label>Personagens<select v-model="form.privacy.characters"><option>ALL</option><option>MAIN_ONLY</option><option>HIDDEN</option></select></label><label>Equipamentos<select v-model="form.privacy.equipment"><option>VISIBLE</option><option>HIDDEN</option></select></label><label>Estatísticas<select v-model="form.privacy.statistics"><option>PRIVATE</option><option>SELECTIVE</option><option>PUBLIC</option></select></label><label>Guild<select v-model="form.privacy.guild"><option>VISIBLE</option><option>HIDDEN</option></select></label><label>Atividade<select v-model="form.privacy.activity"><option>VISIBLE</option><option>HIDDEN</option></select></label></section></div><footer><UButton color="neutral" variant="soft" @click="emit('close')">Cancelar</UButton><UButton color="error" type="submit"><Save class="size-4" />Salvar perfil</UButton></footer></form></div></Teleport></template>
<style scoped>
.community-editor-backdrop{position:fixed;z-index:100;inset:0;display:grid;place-items:center;background:rgb(16 16 16/.55);padding:18px;backdrop-filter:blur(3px)}.community-editor{width:min(860px,100%);max-height:min(780px,92vh);overflow-y:auto;border:1px solid var(--bm-border-strong);border-radius:10px;background:var(--bm-surface-strong);box-shadow:0 24px 70px rgb(0 0 0/.35);color:var(--bm-text)}.community-editor>header,.community-editor>footer{position:sticky;z-index:2;display:flex;align-items:center;justify-content:space-between;background:var(--bm-surface-strong);padding:14px 18px}.community-editor>header{top:0;border-bottom:1px solid var(--bm-border)}.community-editor>footer{bottom:0;justify-content:flex-end;gap:8px;border-top:1px solid var(--bm-border)}.community-editor header span{color:var(--bm-red);font-size:.58rem;font-weight:900;text-transform:uppercase}.community-editor h2{font-family:Cinzel,serif;font-size:1.1rem}.community-editor__body{display:grid;grid-template-columns:1fr 1fr;gap:18px;padding:18px}.community-editor section{display:grid;align-content:start;gap:10px}.community-editor section h3{border-bottom:1px solid var(--bm-border);padding-bottom:8px;color:var(--bm-wine);font-size:.68rem;font-weight:900;text-transform:uppercase}.community-editor label{display:grid;gap:5px;color:var(--bm-muted);font-size:.62rem;font-weight:800}.community-editor input,.community-editor textarea,.community-editor select{min-height:38px;border:1px solid var(--bm-border);border-radius:6px;background:var(--bm-surface);padding:8px 10px;outline:none;color:var(--bm-text);font-size:.72rem}.community-editor textarea{min-height:90px;resize:vertical}.community-editor input:focus,.community-editor textarea:focus,.community-editor select:focus{border-color:var(--bm-red)}.community-editor small{color:var(--bm-muted);font-size:.58rem;line-height:1.5}.community-editor__two,.community-editor__privacy{display:grid;grid-template-columns:1fr 1fr;gap:10px}.community-editor__privacy{grid-column:1/-1}.community-editor__privacy h3{grid-column:1/-1}@media(max-width:680px){.community-editor__body{grid-template-columns:1fr}.community-editor__privacy{grid-template-columns:1fr 1fr}.community-editor-backdrop{padding:8px}}
</style>
