import { randomUUID } from 'node:crypto'
import { ConflictException, Injectable } from '@nestjs/common'
import type { GameAccountIdentity, GameProvisioningStatus } from '@prisma/client'
import { PrismaService } from '../../database/prisma.service'

// Phase 3B. Portal-side scaffold for the Unified Blood Moon Account model
// -- see docs/game-data/unified-account.md and
// docs/game-data/game-account-provisioning-contract.md. No GameBridge
// command exists yet; nothing here ever writes to MU SQL.
//
// State machine (docs/game-data/game-account-provisioning-contract.md
// Part F): PENDING -> PROVISIONING -> ACTIVE, with PROVISIONING -> FAILED
// -> PROVISIONING (retry) as the only other legal path. Every other
// transition is rejected -- there is no "arbitrary state mutation" here,
// by construction (a fixed allow-list, checked before every write).
//
// GAME_READY semantics (Part G): ACTIVE *is* GAME_READY. There is no
// separate gameReady flag -- that would be a redundant second source of
// truth for the same fact.
const ALLOWED_TRANSITIONS: Record<GameProvisioningStatus, GameProvisioningStatus[]> = {
  PENDING: ['PROVISIONING'],
  PROVISIONING: ['ACTIVE', 'FAILED'],
  ACTIVE: [],
  FAILED: ['PROVISIONING']
}

export class InvalidProvisioningTransitionError extends ConflictException {
  constructor(from: GameProvisioningStatus, to: GameProvisioningStatus) {
    super(`Cannot transition GameAccountIdentity from ${from} to ${to}`)
  }
}

@Injectable()
export class GameAccountIdentityService {
  constructor(private readonly prisma: PrismaService) {}

  // Part H: the idempotency anchor. Generated ONCE, here, and never
  // regenerated by a retry -- retry() below reuses the existing row's
  // provisioningRequestId, it never creates a new one.
  buildPendingCreateInput(): { provisioningStatus: 'PENDING'; provisioningRequestId: string } {
    return { provisioningStatus: 'PENDING', provisioningRequestId: randomUUID() }
  }

  // Idempotent: an account can have at most one GameAccountIdentity
  // (accountId is @unique on the model). Calling this for an account
  // that already has one returns the existing row rather than creating
  // a second -- this is what makes a retried "request provisioning"
  // action safe to call more than once.
  async ensurePendingForAccount(accountId: string): Promise<GameAccountIdentity> {
    const existing = await this.prisma.gameAccountIdentity.findUnique({ where: { accountId } })
    if (existing) {
      return existing
    }
    return this.prisma.gameAccountIdentity.create({
      data: { accountId, ...this.buildPendingCreateInput() }
    })
  }

  async findByAccountId(accountId: string): Promise<GameAccountIdentity | null> {
    return this.prisma.gameAccountIdentity.findUnique({ where: { accountId } })
  }

  async transitionToProvisioning(id: string): Promise<GameAccountIdentity> {
    return this.applyTransition(id, 'PROVISIONING', (data) => ({
      ...data,
      lastAttemptAt: new Date()
    }))
  }

  async markActive(id: string, membGuid: number, legacyLogin: string): Promise<GameAccountIdentity> {
    return this.applyTransition(id, 'ACTIVE', (data) => ({
      ...data,
      membGuid,
      legacyLogin,
      provisionedAt: new Date(),
      lastErrorCode: null
    }))
  }

  async markFailed(id: string, errorCode: string): Promise<GameAccountIdentity> {
    return this.applyTransition(id, 'FAILED', (data) => ({
      ...data,
      lastErrorCode: errorCode
    }))
  }

  // Part H: retry reuses the same row (same provisioningRequestId) --
  // it never creates a new GameAccountIdentity and never generates a new
  // provisioningRequestId, which is exactly what makes a future
  // CREATE_GAME_ACCOUNT retry safe from double-provisioning.
  async retry(id: string): Promise<GameAccountIdentity> {
    return this.applyTransition(id, 'PROVISIONING', (data) => ({
      ...data,
      lastAttemptAt: new Date()
    }))
  }

  private async applyTransition(
    id: string,
    to: GameProvisioningStatus,
    extra: (data: Record<string, unknown>) => Record<string, unknown>
  ): Promise<GameAccountIdentity> {
    const current = await this.prisma.gameAccountIdentity.findUniqueOrThrow({ where: { id } })
    if (!ALLOWED_TRANSITIONS[current.provisioningStatus].includes(to)) {
      throw new InvalidProvisioningTransitionError(current.provisioningStatus, to)
    }
    return this.prisma.gameAccountIdentity.update({
      where: { id },
      data: extra({ provisioningStatus: to })
    })
  }

  // Part G: the single authoritative GAME_READY check -- callers (e.g.
  // the future Launcher /me endpoint) use this instead of re-deriving
  // "is this account game-ready" from provisioningStatus themselves.
  static isGameReady(identity: GameAccountIdentity | null): boolean {
    return identity?.provisioningStatus === 'ACTIVE' && identity.membGuid !== null
  }
}
