<template>
  <section class="grid gap-4">
    <header class="flex flex-wrap items-end justify-between gap-3"><div><p class="bm-kicker">Catalogo</p><h2 class="mt-1 font-display text-2xl font-black uppercase text-white">Equipamentos e itens exclusivos</h2></div><button class="bm-admin-primary" type="button" @click="createNew"><Plus :size="16" /> Novo item</button></header>
    <div class="grid gap-2 rounded-md border border-white/10 bg-black/20 p-3 md:grid-cols-[1fr_190px_170px]"><input v-model="search" class="bm-admin-field" type="search" placeholder="Buscar equipamento"><select v-model="group" class="bm-admin-field"><option value="">Todos os grupos</option><option v-for="item in metadata.groups" :key="item" :value="item">{{ item }}</option></select><select v-model="status" class="bm-admin-field"><option value="">Todos os status</option><option v-for="item in metadata.statuses" :key="item" :value="item">{{ item }}</option></select></div>
    <p v-if="message" class="rounded-md border border-white/10 bg-white/7 px-3 py-2 text-xs font-bold text-white/75">{{ message }}</p>
    <div class="overflow-hidden rounded-md border border-white/10"><article v-for="item in rows" :key="item.id" class="grid gap-3 border-b border-white/10 bg-black/18 p-3 last:border-0 md:grid-cols-[1fr_120px_110px_160px_auto] md:items-center"><div><strong class="text-sm text-white">{{ item.name }}</strong><p class="mt-1 text-xs text-white/48">{{ item.key }}</p></div><span class="bm-admin-chip">{{ item.group }}</span><span class="text-xs font-black text-ember">S{{ item.minSeason }}</span><span class="text-xs font-bold text-white/55">{{ item.pieces?.length || 0 }} pecas · {{ item.variants?.length || 0 }} variantes</span><div class="flex gap-2"><button class="bm-admin-action" type="button" @click="edit(item.id)"><Pencil :size="14" /> Editar</button><button class="bm-admin-danger" type="button" @click="archive(item)"><Archive :size="14" /></button></div></article><p v-if="!rows.length" class="p-8 text-center text-sm font-bold text-white/45">Nenhum equipamento encontrado.</p></div>

    <CmsModal :open="modalOpen" :title="form.id ? 'Editar equipamento' : 'Novo equipamento'" @close="modalOpen = false">
      <form class="grid gap-5" @submit.prevent="save">
        <section class="grid gap-3 md:grid-cols-2"><label class="bm-admin-label">Nome<input v-model="form.name" required class="bm-admin-field"></label><label class="bm-admin-label">Chave<input v-model="form.key" class="bm-admin-field" placeholder="Gerada automaticamente"></label><label class="bm-admin-label">Categoria<input v-model="form.category" class="bm-admin-field"></label><label class="bm-admin-label">Grupo<select v-model="form.group" class="bm-admin-field"><option v-for="item in metadata.groups" :key="item" :value="item">{{ item }}</option></select></label><label class="bm-admin-label">Season minima<input v-model.number="form.minSeason" class="bm-admin-field" type="number" min="1" max="6"></label><label class="bm-admin-label">Status<select v-model="form.status" class="bm-admin-field"><option v-for="item in metadata.statuses" :key="item" :value="item">{{ item }}</option></select></label></section>

        <section class="bm-admin-subpanel"><h3 class="bm-admin-section-title">Variantes</h3><div class="mt-3 flex flex-wrap gap-2"><label v-for="quality in metadata.qualities" :key="quality" class="flex items-center gap-2 rounded-md border border-white/10 bg-black/20 px-3 py-2 text-xs font-bold text-white/70"><input v-model="form.qualities" type="checkbox" :value="quality"> {{ quality }}</label></div></section>

        <section class="bm-admin-subpanel"><div class="flex items-center justify-between"><h3 class="bm-admin-section-title">Pecas do equipamento</h3><button class="bm-admin-action" type="button" @click="form.pieces.push(newPiece())"><Plus :size="14" /> Peca</button></div><div class="mt-3 grid gap-2"><div v-for="(piece, index) in form.pieces" :key="index" class="grid gap-2 rounded-md border border-white/10 bg-black/15 p-2 md:grid-cols-[1fr_150px_220px_auto] md:items-center"><input v-model="piece.name" class="bm-admin-field" placeholder="Nome"><input v-model="piece.slot" class="bm-admin-field" placeholder="Slot"><div class="flex min-w-0 items-center gap-2"><img v-if="piece.imagePath" :src="piece.imagePath" :alt="piece.imageName || piece.name" class="h-12 w-12 shrink-0 rounded border border-white/12 object-contain"><div v-else class="grid h-12 w-12 shrink-0 place-items-center rounded border border-dashed border-white/20 text-white/35"><ImageIcon :size="18" /></div><div class="min-w-0"><label class="bm-admin-action cursor-pointer"><Upload :size="14" /> {{ piece.imagePath ? 'Substituir' : 'Selecionar' }}<input class="sr-only" type="file" accept="image/png,image/jpeg,image/webp" @change="uploadPieceImage($event, piece)"></label><p class="mt-1 truncate text-[10px] font-bold text-white/45">{{ piece.uploading ? 'Enviando...' : (piece.imageName || 'Sem imagem') }}</p></div><button v-if="piece.imagePath" class="bm-admin-danger" type="button" title="Remover imagem" @click="removePieceImage(piece)"><X :size="14" /></button></div><button class="bm-admin-danger" type="button" title="Remover peca" @click="form.pieces.splice(index, 1)"><Trash2 :size="14" /></button></div></div></section>

        <section class="bm-admin-subpanel"><div class="flex items-center justify-between"><h3 class="bm-admin-section-title">Opcoes e bonus</h3><button class="bm-admin-action" type="button" @click="form.options.push(newOption())"><Plus :size="14" /> Opcao</button></div><div class="mt-3 grid gap-2"><div v-for="(option, index) in form.options" :key="index" class="grid gap-2 md:grid-cols-[180px_1fr_auto]"><input v-model="option.scope" class="bm-admin-field" placeholder="Escopo"><input v-model="option.label" class="bm-admin-field" placeholder="Descricao do bonus"><button class="bm-admin-danger" type="button" @click="form.options.splice(index, 1)"><Trash2 :size="14" /></button></div></div></section>

        <section class="bm-admin-subpanel"><h3 class="bm-admin-section-title">Classes permitidas</h3><div class="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><article v-for="character in metadata.characters" :key="character.id" class="rounded-md border border-white/10 bg-black/20 p-3"><strong class="text-sm text-white">{{ character.name }}</strong><label v-for="gameClass in character.classes" :key="gameClass.id" class="mt-2 flex items-center gap-2 text-xs font-bold text-white/62"><input v-model="form.classIds" type="checkbox" :value="gameClass.id"> {{ gameClass.name }}</label></article></div></section>

        <section class="bm-admin-subpanel"><label class="bm-admin-label">Temporadas disponiveis<input v-model="form.seasons" class="bm-admin-field" placeholder="Ex.: 1, 2, 6, 21"></label></section>
        <div class="flex justify-end gap-2"><button class="bm-admin-action" type="button" @click="modalOpen = false">Cancelar</button><button class="bm-admin-primary" :disabled="saving" type="submit"><Save :size="16" /> {{ saving ? 'Salvando...' : 'Salvar equipamento' }}</button></div>
      </form>
    </CmsModal>
  </section>
</template>

<script setup lang="ts">
import { Archive, Image as ImageIcon, Pencil, Plus, Save, Trash2, Upload, X } from 'lucide-vue-next'
type GameClass = { id: string; characterId: string; name: string }
type Character = { id: string; name: string; classes: GameClass[] }
type Metadata = { groups: string[]; qualities: string[]; scopes: string[]; statuses: string[]; characters: Character[] }
type Equipment = { id: string; key: string; name: string; title: string; category: string; group: string; minSeason: number; status: string; pieces?: Array<{ name: string; slot: string; imagePath?: string | null }>; variants?: Array<{ quality: string }>; options?: Array<{ scope: string; label: string }>; seasons?: Array<{ season: number }>; classLinks?: Array<{ classId: string; role: string }> }
const api = useAdminContentApi(); const metadata = reactive<Metadata>({ groups: [], qualities: [], scopes: [], statuses: [], characters: [] }); const rows = ref<Equipment[]>([]); const search = ref(''); const group = ref(''); const status = ref(''); const modalOpen = ref(false); const saving = ref(false); const message = ref('')
const newPiece = () => ({ name: '', slot: '', imagePath: '', imageName: '', uploading: false }); const newOption = () => ({ scope: 'general', label: '' })
const emptyForm = () => ({ id: '', key: '', name: '', category: 'Custom', group: 'MISC', minSeason: 6, status: 'RAW', qualities: ['NORMAL'] as string[], pieces: [] as ReturnType<typeof newPiece>[], options: [] as ReturnType<typeof newOption>[], classIds: [] as string[], classRoles: {} as Record<string, string>, seasons: '6' })
const form = reactive(emptyForm()); let timer: ReturnType<typeof setTimeout> | undefined
const classById = computed(() => new Map(metadata.characters.flatMap((character) => character.classes.map((gameClass) => [gameClass.id, gameClass]))))
const load = async () => { const [items, meta] = await Promise.all([api.equipment({ pageSize: 100, search: search.value, group: group.value, status: status.value }), api.equipmentMetadata()]) as [{ data: Equipment[] }, Metadata]; rows.value = items.data; Object.assign(metadata, meta) }
watch([search, group, status], () => { clearTimeout(timer); timer = setTimeout(() => void load(), 250) }); onMounted(() => void load())
const createNew = () => { Object.assign(form, emptyForm()); modalOpen.value = true }
const edit = async (id: string) => { const item = await api.equipmentDetail(id) as Equipment; Object.assign(form, emptyForm(), { id: item.id, key: item.key, name: item.name, category: item.category, group: item.group, minSeason: item.minSeason, status: item.status, qualities: item.variants?.map((variant) => variant.quality) || [], pieces: item.pieces?.map((piece) => ({ name: piece.name, slot: piece.slot, imagePath: piece.imagePath || '', imageName: piece.imagePath ? `Imagem de ${piece.name}` : '', uploading: false })) || [], options: item.options?.map((option) => ({ scope: option.scope, label: option.label })) || [], classIds: item.classLinks?.map((link) => link.classId) || [], classRoles: Object.fromEntries(item.classLinks?.map((link) => [link.classId, link.role]) || []), seasons: item.seasons?.map((season) => season.season).join(', ') || String(item.minSeason) }); modalOpen.value = true }
const uploadPieceImage = async (event: Event, piece: ReturnType<typeof newPiece>) => { const input = event.target as HTMLInputElement; const file = input.files?.[0]; input.value = ''; if (!file) return; if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { message.value = 'Selecione uma imagem PNG, JPEG ou WebP de ate 5 MB.'; return } piece.uploading = true; try { const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file) }); const uploaded = await api.uploadImage({ name: file.name.replace(/\.[^.]+$/, ''), dataUrl }); piece.imagePath = uploaded.url; piece.imageName = uploaded.name; message.value = 'Imagem enviada com sucesso.' } catch { message.value = 'Nao foi possivel enviar a imagem. Tente novamente.' } finally { piece.uploading = false } }
const removePieceImage = (piece: ReturnType<typeof newPiece>) => { piece.imagePath = ''; piece.imageName = '' }
const save = async () => { saving.value = true; try { const seasons = [...new Set(form.seasons.split(',').map(Number).filter((item) => Number.isInteger(item) && item > 0 && item <= 6))]; const payload = { key: form.key, name: form.name, title: form.name, category: form.category, group: form.group, minSeason: Math.min(form.minSeason, 6), status: form.status, variants: form.qualities.map((quality) => ({ quality, minSeason: Math.min(form.minSeason, 6) })), pieces: form.pieces.filter((piece) => piece.name && piece.slot), options: form.options.filter((option) => option.label), classLinks: form.classIds.map((classId) => ({ classId, characterId: classById.value.get(classId)?.characterId, role: form.classRoles[classId] || 'PLAYABLE', source: 'admin' })).filter((link) => link.characterId), seasons: seasons.map((season) => ({ season, visibility: 'SEASON_6', source: 'admin' })) }; form.id ? await api.updateEquipment(form.id, payload) : await api.createEquipment(payload); modalOpen.value = false; message.value = 'Equipamento salvo por completo e registrado na auditoria.'; await load() } catch { message.value = 'Nao foi possivel salvar o equipamento. Verifique campos e duplicidades.' } finally { saving.value = false } }
const archive = async (item: Equipment) => { if (!confirm(`Arquivar ${item.name}?`)) return; await api.archiveEquipment(item.id); message.value = 'Equipamento arquivado e registrado na auditoria.'; await load() }
</script>
