<template>
  <section class="grid gap-4">
    <header class="flex flex-wrap items-end justify-between gap-3"><div><p class="bm-kicker">Sistema</p><h2 class="mt-1 font-display text-2xl font-black uppercase text-white">Configuracoes do site e servidor</h2><p class="mt-2 text-xs font-bold text-white/52">Segredos e credenciais continuam exclusivamente no ambiente do servidor e nunca devem ser cadastrados aqui.</p></div><button class="bm-admin-primary" type="button" @click="createNew"><Plus :size="16" /> Nova configuracao</button></header>
    <div class="grid gap-2 rounded-md border border-white/10 bg-black/20 p-3 md:grid-cols-[1fr_190px]"><input v-model="search" class="bm-admin-field" type="search" placeholder="Buscar configuracao"><select v-model="category" class="bm-admin-field"><option value="">Todas as categorias</option><option v-for="item in categories" :key="item" :value="item">{{ item }}</option></select></div>
    <p v-if="message" class="rounded-md border border-white/10 bg-white/7 px-3 py-2 text-xs font-bold text-white/75">{{ message }}</p>
    <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><article v-for="item in rows" :key="item.id" class="rounded-md border border-white/10 bg-black/20 p-4"><div class="flex items-start justify-between gap-3"><div><span class="bm-admin-chip">{{ item.category }}</span><h3 class="mt-3 text-sm font-black text-white">{{ item.label }}</h3><p class="mt-1 font-mono text-[11px] text-white/42">{{ item.key }}</p></div><span class="bm-admin-chip">{{ item.isPublic ? 'PUBLICA' : 'PRIVADA' }}</span></div><p class="mt-3 line-clamp-3 text-xs font-bold leading-5 text-white/55">{{ displayValue(item.value) }}</p><div class="mt-4 flex gap-2"><button class="bm-admin-action" type="button" @click="edit(item)"><Pencil :size="14" /> Editar</button><button class="bm-admin-danger" type="button" @click="archive(item)"><Archive :size="14" /></button></div></article></div>

    <CmsModal :open="modalOpen" :title="form.id ? 'Editar configuracao' : 'Nova configuracao'" @close="modalOpen = false">
      <form class="grid gap-4" @submit.prevent="save"><div class="grid gap-3 md:grid-cols-2"><label class="bm-admin-label">Chave<input v-model="form.key" required class="bm-admin-field" placeholder="server-xp-rate"></label><label class="bm-admin-label">Categoria<input v-model="form.category" required class="bm-admin-field" placeholder="servidor"></label><label class="bm-admin-label md:col-span-2">Nome amigavel<input v-model="form.label" required class="bm-admin-field"></label></div><label class="bm-admin-label">Descricao<textarea v-model="form.description" class="bm-admin-field min-h-20" /></label><label class="bm-admin-label">Valor<textarea v-model="form.valueText" required class="bm-admin-field min-h-32" placeholder='Texto simples, numero, booleano ou JSON: {"ativo":true}' /></label><div class="grid gap-3 md:grid-cols-2"><label class="bm-admin-label">Status<select v-model="form.status" class="bm-admin-field"><option v-for="item in statuses" :key="item" :value="item">{{ item }}</option></select></label><label class="mt-6 flex items-center gap-2 text-sm font-bold text-white/70"><input v-model="form.isPublic" type="checkbox"> Pode ser exposta no site publico</label></div><p class="rounded-md border border-amber-400/20 bg-amber-400/8 p-3 text-xs font-bold text-amber-100/75">Nao insira senhas, tokens, strings de banco ou chaves privadas. Esses valores pertencem ao arquivo de ambiente do servidor.</p><div class="flex justify-end gap-2"><button class="bm-admin-action" type="button" @click="modalOpen = false">Cancelar</button><button class="bm-admin-primary" :disabled="saving" type="submit"><Save :size="16" /> Salvar</button></div></form>
    </CmsModal>
  </section>
</template>

<script setup lang="ts">
import { Archive, Pencil, Plus, Save } from 'lucide-vue-next'
type Setting = { id: string; key: string; category: string; label: string; description?: string | null; value: unknown; isPublic: boolean; status: string }
const api = useAdminContentApi(); const rows = ref<Setting[]>([]); const search = ref(''); const category = ref(''); const message = ref(''); const modalOpen = ref(false); const saving = ref(false); const statuses = ['RAW', 'REVIEWED', 'APPROVED', 'PUBLISHED', 'ARCHIVED']; const categories = computed(() => [...new Set(rows.value.map((item) => item.category))])
const emptyForm = () => ({ id: '', key: '', category: 'geral', label: '', description: '', valueText: '', isPublic: false, status: 'PUBLISHED' }); const form = reactive(emptyForm()); let timer: ReturnType<typeof setTimeout> | undefined
const load = async () => { try { const result = await api.settings({ pageSize: 100, search: search.value, category: category.value }) as { data: Setting[] }; rows.value = result.data } catch { message.value = 'Falha ao carregar configuracoes.' } }
watch([search, category], () => { clearTimeout(timer); timer = setTimeout(load, 250) }); onMounted(load)
const displayValue = (value: unknown) => typeof value === 'string' ? value : JSON.stringify(value)
const createNew = () => { Object.assign(form, emptyForm()); modalOpen.value = true }
const edit = (item: Setting) => { Object.assign(form, item, { valueText: typeof item.value === 'string' ? item.value : JSON.stringify(item.value, null, 2) }); modalOpen.value = true }
const parseValue = (value: string) => { const trimmed = value.trim(); try { return JSON.parse(trimmed) } catch { return trimmed } }
const save = async () => { saving.value = true; try { const payload = { key: form.key, category: form.category, label: form.label, description: form.description, value: parseValue(form.valueText), isPublic: form.isPublic, status: form.status }; form.id ? await api.updateSetting(form.id, payload) : await api.createSetting(payload); modalOpen.value = false; message.value = 'Configuracao salva e registrada na auditoria.'; await load() } catch { message.value = 'Nao foi possivel salvar. Verifique se a chave ja existe.' } finally { saving.value = false } }
const archive = async (item: Setting) => { if (!confirm(`Arquivar ${item.label}?`)) return; await api.archiveSetting(item.id); message.value = 'Configuracao arquivada e registrada na auditoria.'; await load() }
</script>
